### ISSUE TITLE
Pay Bot

### ISSUE THREAD

**Issue by davisfigueiredo** [mole3421278/Daibotuten-futures-trading-optimizer-bot#12]
Today I paid the 10 dollars for the Daibot. But I didn't get access. In the application the status remains inactive. I deposited through the Tron network at 16:19 (São Paulo - Brazil) Can you help me?
 Thank you very much for your attention.

Status
Completed
Date
2022-08-22 16:17
Withdraw wallet
Spot Wallet
Coin
USDT
Withdraw amount
10
Network fee
0.8
Network
TRX
Address
TFrQ9hfueNT5EBaAnTeBru8Wg2H9dKQRxY
TxID
80a5e2fcf41bd8e9420c43a1af127ebd3f9aa787ea9a5636d021e29919a7e622

**Comment by mole3421278** [comment]
Hello,
sorry for the late answer,
the bot isn't active because of this:
"To pay the fee you can send the equivalent of 15 usdt for the first time (activation + monthly fee) or the equivalent of 10 usdt for the other times (for the monthly fee)"
as written in https://github.com/mole3421278/Daibotuten-futures-trading-optimizer-bot#devs-fee

I suppose this is the first time you're trying to use the bot, so there is the cost for the activation.
I can send back the quantity to the address to redo the operation of activation.
