### ISSUE TITLE
Enhancement propositions

### ISSUE THREAD

**Issue by orsson9** [mole3421278/Daibotuten-futures-trading-optimizer-bot#8]
Got 2 following enhancements:

- Save some profit and send it other user binance wallet like spot wallet.
When bot is closing postion with profit, part of the profit could be transferred to spot wallet. User have option to configure % of profit sended to other wallet. 

- Bot stop buying new postions when wallet balance goes down to certain postions.
Let's say user have 200 usdt wallet balance. User have option to set protected amount to for example 100 usdt. When we enter bear market and bot is starting to loosing money, he should stop buing new postions when balance fells below 100 usdt. (Opened postions should still remain open). Optionally, bot could resume buying when certain conditions appear.

**Comment by mole3421278** [comment]
Hello orsson9,
nice proposals. Both of them approved.
Talking about the second one, after the conditions that resumes the bot are satisfied, if the wallet balance is still under the threshold of protection, then it can happen three things:
- the bot doesn't resume because it must have at least the balance the user chose as threshold;
- the threshold is now ignored and if the bear market continues it doesn't protect anymore;
- the threshold is moved below in percentage to another new threshold.
I think the third option is the best, even if it is less transparent to the user in the case where the bear market continues and the threshold is moved a lot of times... 
Also the conditions to resume the bot must be investigated. Maybe it can be set that after BTC rises of at least a certain percentage the bot resumes.
Will think about it and implement them.
If you have other suggestions for the condition and the threshold, you can write them here.
Thank you for your support.

**Comment by mole3421278** [comment]
For the condition can be used the liquidations of the whales: when, after the threshold has been reached, the number of short liquidations becomes greater than the number of long liquidations plus a certain value, then resume the bot.

**Comment by orsson9** [comment]
Thanks appreciate that proposals are approved.

Regarding the wallet balance protection I also choose 3 option.
About resume I was thinking about monitoring fear and greed index or alt season index but they are updated only once per day, so btc liquidations sounds more reasonable.

**Comment by mole3421278** [comment]
Yeah, was thinking about that indices too, but arrived at the same conclusion. So better this way.
Also, going to add another new feature: in the config file there will be the possibility to set for specific cryptocurrencies the price to buy only below it and the price to sell only above it.
Examples of different use cases:
Avax 80 - 85
to buy Avax only if its price is under 80 usdt and to sell it only if its price is over 85 usdt
Avax 85 - 80
to buy Avax only if its price is under 85 usdt and to sell it only if its price is over 80 usdt
Avax 80 -
to buy Avax only if its price is under 80 usdt and no limits to sell it
Avax - 85
to sell Avax only if its price is over 85 usdt and no limits to buy it
Avax 85
to buy Avax only if its price is under 85 usdt and to sell it only if its price is over 85 usdt

**Comment by mole3421278** [comment]
Implemented. Closing this issue in a few days if nothing will be added, 
thank you
