### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Pusherman2** [mole3421278/Daibotuten-futures-trading-optimizer-bot#9]
Edit: Can be closed.

**Comment by mole3421278** [comment]
Sorry, I arrived late... I think the problem was with the permission for the API key. The tick on Enable Futures is mandatory, otherwise the bot won't work.

Feel free to reopen an issue for any kind of problem and always be sure to moderate your exposure: we never know when a crash occurs, so it's always good not to put too many funds all together on futures. Good trading!

**Comment by Pusherman2** [comment]
Hi there Mole,

Thank you for your reply. The issue with the balance showing 0.0 does not impact opening positions so it is resolved.

I do however, have some additional questions if you don't mind:
At some point the bot will open a lot of positions but they don't show up in the main interface. Will the bot also manage the positions which do not show up in the GUI but are opened on the exchange?

And also if I set the TP/SL value to 0, does the bot handle the closing of the position with a TP/SL automatically or do I need to set a TP/SL myself?

Kind regards,

Pusherman

**Comment by mole3421278** [comment]
Hello Pusherman2,

so the balance you see is still 0.0 usdt? Even after closing some positions does it remain 0.0 usdt? 

Are you sure that the positions aren't displayed in the main interface? When the main interface is full, you can scroll it down to see the other positions. Check if you can the others scrolling down.

Setting the TP/SL value to 0, the bot will use its algorithm to close the positions. When you set them to other values you overwrite its behavior. The values I suggest to change depending on the market are the others, like "don't buy if btc is".
